# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "Babel" = super.buildPythonPackage rec {
    pname = "Babel";
    version = "2.14.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0d/35/4196b21041e29a42dc4f05866d0c94fa26c9da88ce12c38c2265e42c82fb/Babel-2.14.0-py3-none-any.whl";
      sha256 = "11vjlnvq36b8hd67hb5dx25vd7628l2x5gjrlbiprrhqf5ds5cgg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "Jinja2" = super.buildPythonPackage rec {
    pname = "Jinja2";
    version = "3.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/30/6d/6de6be2d02603ab56e72997708809e8a5b0fbfee080735109b40a3564843/Jinja2-3.1.3-py3-none-any.whl";
      sha256 = "1ymmf31yhp5376g6368z3rakzb7vmdgq9gcpalsvqb6mjzfm0vbx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "MarkupSafe" = super.buildPythonPackage rec {
    pname = "MarkupSafe";
    version = "2.1.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/87/5b/aae44c6655f3801e81aa3eef09dbbf012431987ba564d7231722f68df02d/MarkupSafe-2.1.5.tar.gz";
      sha256 = "0jslqq4sgl8bq1ivnyr4q9xnxirmch2gibgzffpc390bi5xd70yj";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "Pygments" = super.buildPythonPackage rec {
    pname = "Pygments";
    version = "2.17.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/9c/372fef8377a6e340b1704768d20daaded98bf13282b5327beb2e2fe2c7ef/pygments-2.17.2-py3-none-any.whl";
      sha256 = "0v44mw2dskc0rmx6926qfm8r9s6561684m4my8ck43vxqhk2hz5j";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "Sphinx" = super.buildPythonPackage rec {
    pname = "Sphinx";
    version = "7.2.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b2/b6/8ed35256aa530a9d3da15d20bdc0ba888d5364441bb50a5a83ee7827affe/sphinx-7.2.6-py3-none-any.whl";
      sha256 = "0q0md5yz146znfkpd60brb9kpabdcgx1h0ci7iidqmmr8051c28y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Babel"
      self."Jinja2"
      self."Pygments"
      self."alabaster"
      self."docutils"
      self."imagesize"
      self."importlib-metadata"
      self."packaging"
      self."requests"
      self."snowballstemmer"
      self."sphinxcontrib-applehelp"
      self."sphinxcontrib-devhelp"
      self."sphinxcontrib-htmlhelp"
      self."sphinxcontrib-jsmath"
      self."sphinxcontrib-qthelp"
      self."sphinxcontrib-serializinghtml"
    ];
  };
  "alabaster" = super.buildPythonPackage rec {
    pname = "alabaster";
    version = "0.7.16";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/32/34/d4e1c02d3bee589efb5dfa17f88ea08bdb3e3eac12bc475462aec52ed223/alabaster-0.7.16-py3-none-any.whl";
      sha256 = "14icisi2hjdzr2v93id7y1hgldspqxsvjc032m7aw0yfgp036rxl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "astroid" = super.buildPythonPackage rec {
    pname = "astroid";
    version = "3.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/1c/ee18acf9070f77253954b7d71b4c0cf8f5969fb23067d8f1a8793573ba00/astroid-3.1.0-py3-none-any.whl";
      sha256 = "068q85s9ziffw3xdgrkhqxq4xaxp7m3sylqc16n3f0cr4bwrh5wm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "23.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e0/44/827b2a91a5816512fcaf3cc4ebc465ccd5d598c45cefa6703fcf4a79018f/attrs-23.2.0-py3-none-any.whl";
      sha256 = "1wf6ixz7mmvrb28vwr7x0asm3fa4bcqc414zhwxv482qb947mf4r";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "bech32" = super.buildPythonPackage rec {
    pname = "bech32";
    version = "1.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b6/41/7022a226e5a6ac7091a95ba36bad057012ab7330b9894ad4e14e31d0b858/bech32-1.2.0-py3-none-any.whl";
      sha256 = "10frg6gdwb3mnccllady83dp76yxbwqva1sjynyspzp4lpjwh3cr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2024.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/06/a07f096c664aeb9f01624f858c3add0a4e913d6c96257acb4fce61e7de14/certifi-2024.2.2-py3-none-any.whl";
      sha256 = "1lfds5aaf96aqr9gcmadx88s011vb4mywvhhyrlg62b1nw3kqf6w";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "charset-normalizer" = super.buildPythonPackage rec {
    pname = "charset-normalizer";
    version = "3.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/63/09/c1bc53dab74b1816a00d8d030de5bf98f724c52c1635e07681d312f20be8/charset-normalizer-3.3.2.tar.gz";
      sha256 = "1m9g0f513ng4dp2vd3smi4g2nmhqkjqh3bzcza14li947frkq37k";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "click" = super.buildPythonPackage rec {
    pname = "click";
    version = "8.1.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl";
      sha256 = "0a0c77rq458xjfkrkdxqinlza5447kby9w8msshpf0haqabgnx5f";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cosmospy-protobuf" = super.buildPythonPackage rec {
    pname = "cosmospy-protobuf";
    version = "0.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/95/66/7fffcc56f3cc220fb69fc220176f0eca6b5aea6881f244906e575f045de8/cosmospy_protobuf-0.4.0-py2.py3-none-any.whl";
      sha256 = "0rl0yz49knna2mb0258iq6rqs7li7lmmkjgg5s7qbkq42r3gc22g";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."protobuf"
    ];
  };
  "cosmpy" = super.buildPythonPackage rec {
    pname = "cosmpy";
    version = "0.9.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/bf/2b5e594858b0d41e372c9e4f975b3e5b2b655af1670f3a600d684d5c68d4/cosmpy-0.9.2-py3-none-any.whl";
      sha256 = "06gsn17m09nbsal0g8psgzqp96b6cshir1a0afkhm2mhk08k349m";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."bech32"
      self."ecdsa"
      self."googleapis-common-protos"
      self."grpcio"
      self."jsonschema"
      self."protobuf"
      self."pycryptodome"
      self."python-dateutil"
      self."requests"
    ];
  };
  "dill" = super.buildPythonPackage rec {
    pname = "dill";
    version = "0.3.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c9/7a/cef76fd8438a42f96db64ddaa85280485a9c395e7df3db8158cfec1eee34/dill-0.3.8-py3-none-any.whl";
      sha256 = "1msvh5z5nqdcn64cwymmaa27y8r159yzygpbz39bsra3npzsjv63";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "docstring-to-markdown" = super.buildPythonPackage rec {
    pname = "docstring-to-markdown";
    version = "0.15";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c1/cf/4eee59f6c4111b3e80cc32cf6bac483a90646f5c8693e84496c9855e8e38/docstring_to_markdown-0.15-py3-none-any.whl";
      sha256 = "1h5fakl80478qjdx5xzdksvzpmsqsaxk472j6d6f70dsxpxb7br7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "docutils" = super.buildPythonPackage rec {
    pname = "docutils";
    version = "0.20.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/26/87/f238c0670b94533ac0353a4e2a1a771a0cc73277b88bff23d3ae35a256c1/docutils-0.20.1-py3-none-any.whl";
      sha256 = "1mjr98g9npd96hxbzsq8mi67cbhrnax3pw89dx3v8banqni8gwwn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ecdsa" = super.buildPythonPackage rec {
    pname = "ecdsa";
    version = "0.18.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/09/d4/4f05f5d16a4863b30ba96c23b23e942da8889abfa1cdbabf2a0df12a4532/ecdsa-0.18.0-py2.py3-none-any.whl";
      sha256 = "1parqpag3zpfxbhdw3x3snd11501sxdjjz0xmawicbzdwxc04q40";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "exceptiongroup" = super.buildPythonPackage rec {
    pname = "exceptiongroup";
    version = "1.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/01/90/79fe92dd413a9cab314ef5c591b5aa9b9ba787ae4cadab75055b0ae00b33/exceptiongroup-1.2.1-py3-none-any.whl";
      sha256 = "1b993f4im00yd9hgfvvzh10m658bzg5m77rh3b9vsnww6bnvjn2j";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "gitdb" = super.buildPythonPackage rec {
    pname = "gitdb";
    version = "4.0.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fd/5b/8f0c4a5bb9fd491c277c21eff7ccae71b47d43c4446c9d0c6cff2fe8c2c4/gitdb-4.0.11-py3-none-any.whl";
      sha256 = "196z78fwy3gyjqb018yg18al13h35l7a1kms9i2dzs1fvmyl18w1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."smmap"
    ];
  };
  "googleapis-common-protos" = super.buildPythonPackage rec {
    pname = "googleapis-common-protos";
    version = "1.63.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dc/a6/12a0c976140511d8bc8a16ad15793b2aef29ac927baa0786ccb7ddbb6e1c/googleapis_common_protos-1.63.0-py2.py3-none-any.whl";
      sha256 = "0ck65nld1wbmx6pydb3b395573xxg2k5823m3xa8ph7p09bzfidf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."protobuf"
    ];
  };
  "grpc-stubs" = super.buildPythonPackage rec {
    pname = "grpc-stubs";
    version = "1.53.0.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e0/86/147d2ccaf9b4b81407734b9abc1152aff39836e8e05be3bf069f9374c021/grpc_stubs-1.53.0.5-py3-none-any.whl";
      sha256 = "1qfv50s29bxnwygh9zidrin95ls7jqypwqmrxcgnl5hvbav3y604";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."grpcio"
    ];
  };
  "grpcio" = super.buildPythonPackage rec {
    pname = "grpcio";
    version = "1.62.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/04/7a/cb869ec6d7f634c0153b4a38ae25bb33699b9307ea17f8cb22b609a46605/grpcio-1.62.2.tar.gz";
      sha256 = "0kcmpp6r81by0sww0mm2bg3bj8vqafc1lw0h5jzaidwn3l3ihxn7";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "grpcio-tools" = super.buildPythonPackage rec {
    pname = "grpcio-tools";
    version = "1.62.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/09/dfb87373a34bf6ce3261d65f8fb102a163c850c72a3e84902777ed44aa1d/grpcio-tools-1.62.2.tar.gz";
      sha256 = "13z1jh7n89l2msd2kx8xd4j0fpmy829q1xg53sa6p3k75dcf3maz";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."grpcio"
      self."protobuf"
      self."setuptools"
    ];
  };
  "grpclib" = super.buildPythonPackage rec {
    pname = "grpclib";
    version = "0.4.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/79/b9/55936e462a5925190d7427e880b3033601d1effd13809b483d13a926061a/grpclib-0.4.7.tar.gz";
      sha256 = "1hr370v3rq0dbdxax4ff5by7xyfc84n7jqg9x2ibf8ibq1byz219";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools"
      self."wheel"
    ];
    propagatedBuildInputs = [
      self."h2"
      self."multidict"
    ];
  };
  "h2" = super.buildPythonPackage rec {
    pname = "h2";
    version = "4.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/e5/db6d438da759efbb488c4f3fbdab7764492ff3c3f953132efa6b9f0e9e53/h2-4.1.0-py3-none-any.whl";
      sha256 = "0vdwfsa70gchp5wx6h34xhz4qn132ffaksfrbxdwjmi2d37np903";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."hpack"
      self."hyperframe"
    ];
  };
  "hpack" = super.buildPythonPackage rec {
    pname = "hpack";
    version = "4.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d5/34/e8b383f35b77c402d28563d2b8f83159319b509bc5f760b15d60b0abf165/hpack-4.0.0-py3-none-any.whl";
      sha256 = "0v4ah59msyl4cgpg0pmjg0c7p1h0y4g09f6ccf09z6nwsgx7d844";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "hyperframe" = super.buildPythonPackage rec {
    pname = "hyperframe";
    version = "6.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d7/de/85a784bcc4a3779d1753a7ec2dee5de90e18c7bcf402e71b51fcf150b129/hyperframe-6.0.1-py3-none-any.whl";
      sha256 = "059as079ffdz0bl63wngqixyarc27axaqfphqjaj3bfqh3yvmihf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/e7/a82b05cf63a603df6e68d59ae6a68bf5064484a0718ea5033660af4b54a9/idna-3.6-py3-none-any.whl";
      sha256 = "0kxjgs79gi0wdsm7r7kpsnwzp405mldq5i1mm2m9yssaqblnfmf0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "imagesize" = super.buildPythonPackage rec {
    pname = "imagesize";
    version = "1.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/62/85c4c919272577931d407be5ba5d71c20f0b616d31a0befe0ae45bb79abd/imagesize-1.4.1-py2.py3-none-any.whl";
      sha256 = "12wdxzldsva0f2cg94xcnwlkgp0g961gv8bwxv81j344iz81i38d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "importlib-metadata" = super.buildPythonPackage rec {
    pname = "importlib-metadata";
    version = "7.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2d/0a/679461c511447ffaf176567d5c496d1de27cbe34a87df6677d7171b2fbd4/importlib_metadata-7.1.0-py3-none-any.whl";
      sha256 = "0w7mn7xcc3s5skjgl374l00yp7qry3kq0wncsqz4h8y2q2b2p5ih";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
  };
  "iniconfig" = super.buildPythonPackage rec {
    pname = "iniconfig";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ef/a6/62565a6e1cf69e10f5727360368e451d4b7f58beeac6173dc9db836a5b46/iniconfig-2.0.0-py3-none-any.whl";
      sha256 = "0x43fyv1hpwpmvvqh73ldcyac9j2hb14mffis8i3nblxlxqmia5n";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "isort" = super.buildPythonPackage rec {
    pname = "isort";
    version = "5.13.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d1/b3/8def84f539e7d2289a02f0524b944b15d7c75dab7628bedf1c4f0992029c/isort-5.13.2-py3-none-any.whl";
      sha256 = "19j7v5rgwiybzdm6bgrdw6pkjabz4d2qg6x67xd0v1l5ilmfg9cc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jedi" = super.buildPythonPackage rec {
    pname = "jedi";
    version = "0.19.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/9f/bc63f0f0737ad7a60800bfd472a4836661adae21f9c2535f3957b1e54ceb/jedi-0.19.1-py2.py3-none-any.whl";
      sha256 = "1q77yn7g2f22a1q5y55gq2nm0jmv5xdcxpscxxx8c0jwzracd0z9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."parso"
    ];
  };
  "jsonschema" = super.buildPythonPackage rec {
    pname = "jsonschema";
    version = "4.21.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/9d/b035d024c62c85f2e2d4806a59ca7b8520307f34e0932fbc8cc75fe7b2d9/jsonschema-4.21.1-py3-none-any.whl";
      sha256 = "0vqw7la2565rmhcp9krd01w6yz0mc5vl1412krpk05p3z9x515kr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."jsonschema-specifications"
      self."referencing"
      self."rpds-py"
    ];
  };
  "jsonschema-specifications" = super.buildPythonPackage rec {
    pname = "jsonschema-specifications";
    version = "2023.12.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ee/07/44bd408781594c4d0a027666ef27fab1e441b109dc3b76b4f836f8fd04fe/jsonschema_specifications-2023.12.1-py3-none-any.whl";
      sha256 = "0g4wdayahc0dp939qj67lzycmafqayxdjy17paibhn28m7rzvr47";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."referencing"
    ];
  };
  "maturin" = super.buildPythonPackage rec {
    pname = "maturin";
    version = "1.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/4c/77135117237c4ef579da90d51a38defb50a332f57e5c94663bad9c793744/maturin-1.5.1.tar.gz";
      sha256 = "1jkdn9af36l4y7ajhr3jkh9l1b7cw0sldgccy5m8dnqfx3n39n1x";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."tomli"
    ];
  };
  "mccabe" = super.buildPythonPackage rec {
    pname = "mccabe";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/27/1a/1f68f9ba0c207934b35b86a8ca3aad8395a3d6dd7921c0686e23853ff5a9/mccabe-0.7.0-py2.py3-none-any.whl";
      sha256 = "0vkv89izh5asv85wlgbfdkfynd6qy2s0f63q35ls9r70dfmk0bbc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "multidict" = super.buildPythonPackage rec {
    pname = "multidict";
    version = "6.0.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f9/79/722ca999a3a09a63b35aac12ec27dfa8e5bb3a38b0f857f7a1a209a88836/multidict-6.0.5.tar.gz";
      sha256 = "1nnq7nkkqpq9y814gbswmvrqsk8r84y58hdky000bxfsbq3h3qzp";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "mypy" = super.buildPythonPackage rec {
    pname = "mypy";
    version = "1.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/72/1e/a587a862c766a755a58b62d8c00aed11b74a15dc415c1bf5da7b607b0efd/mypy-1.9.0.tar.gz";
      sha256 = "0x7rgaf56zmzwnym96yf465639wpd94nhq4hvp6pi9764w0xmi9w";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."mypy-extensions"
      self."tomli"
      self."typing-extensions"
    ];
  };
  "mypy-extensions" = super.buildPythonPackage rec {
    pname = "mypy-extensions";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/e2/5d3f6ada4297caebe1a2add3b126fe800c96f56dbe5d1988a2cbe0b267aa/mypy_extensions-1.0.0-py3-none-any.whl";
      sha256 = "0bam8jwfajm34qnwrd9jzp6fj2qglzznil93ksk6hmlaxg0gd4j3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "mypy-protobuf" = super.buildPythonPackage rec {
    pname = "mypy-protobuf";
    version = "3.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e8/73/d6b999782ae22f16971cc05378b3b33f6a89ede3b9619e8366aa23484bca/mypy_protobuf-3.6.0-py3-none-any.whl";
      sha256 = "0v7xj8ad5wa8hi33s454xgy7x6xlg0j2c8561qsyfw4har6nw5sn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."protobuf"
      self."types-protobuf"
    ];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "24.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/49/df/1fceb2f8900f8639e278b056416d49134fb8d84c5942ffaa01ad34782422/packaging-24.0-py3-none-any.whl";
      sha256 = "1i8b2dw7fxz3xb94m5pcmg79d0i8rinbmirlqa2bfbzhzm9vbprd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "parso" = super.buildPythonPackage rec {
    pname = "parso";
    version = "0.8.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c6/ac/dac4a63f978e4dcb3c6d3a78c4d8e0192a113d288502a1216950c41b1027/parso-0.8.4-py2.py3-none-any.whl";
      sha256 = "061zsi1hchimzjzi538yxrw16yf3qmvw706wvp9aq7994056f654";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "platformdirs" = super.buildPythonPackage rec {
    pname = "platformdirs";
    version = "4.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/55/72/4898c44ee9ea6f43396fbc23d9bfaf3d06e01b83698bdf2e4c919deceb7c/platformdirs-4.2.0-py3-none-any.whl";
      sha256 = "0s70fnffhzz1cwsd9ilvj8r8dkrcp4jjp3mxmiiadq9p5wmdy506";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pluggy" = super.buildPythonPackage rec {
    pname = "pluggy";
    version = "1.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a5/5b/0cc789b59e8cc1bf288b38111d002d8c5917123194d45b29dcdac64723cc/pluggy-1.4.0-py3-none-any.whl";
      sha256 = "10c9gfqcy4l0hdjqda19h4l1r34anpmp75zmjmdiqzfn0fszgfbx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "protobuf" = super.buildPythonPackage rec {
    pname = "protobuf";
    version = "4.25.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5e/d8/65adb47d921ce828ba319d6587aa8758da022de509c3862a70177a958844/protobuf-4.25.3.tar.gz";
      sha256 = "0p6cj9a6mkmwlqkh9099ngrkar397fg382w3sw5k406h5ysd1d95";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pycryptodome" = super.buildPythonPackage rec {
    pname = "pycryptodome";
    version = "3.20.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/ed/19223a0a0186b8a91ebbdd2852865839237a21c74f1fbc4b8d5b62965239/pycryptodome-3.20.0.tar.gz";
      sha256 = "19zxzyqpvjgspx67xbqzbfqzi4pqzg2cii8caqmirrkxxl4r4q09";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pylint" = super.buildPythonPackage rec {
    pname = "pylint";
    version = "3.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4d/2b/dfcf298607c73c3af47d5a699c3bd84ba580f1b8642a53ba2a53eead7c49/pylint-3.1.0-py3-none-any.whl";
      sha256 = "0x3bzn3xk28zz6szqp1l4s5hagpnga68wvini9npcx1qjmh5nyjh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."astroid"
      self."dill"
      self."isort"
      self."mccabe"
      self."platformdirs"
      self."tomli"
      self."tomlkit"
      self."typing-extensions"
    ];
  };
  "pytest" = super.buildPythonPackage rec {
    pname = "pytest";
    version = "8.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4d/7e/c79cecfdb6aa85c6c2e3cf63afc56d0f165f24f5c66c03c695c4d9b84756/pytest-8.1.1-py3-none-any.whl";
      sha256 = "1dvqpdi9dxczji5lr8x7f02gk3l9gmzabcp71v2x5a8zq77qd0ra";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."exceptiongroup"
      self."iniconfig"
      self."packaging"
      self."pluggy"
      self."tomli"
    ];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.9.0.post0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateutil-2.9.0.post0-py2.py3-none-any.whl";
      sha256 = "09q48zvsbagfa3w87zkd2c5xl54wmb9rf2hlr20j4a5fzxxvrcm8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "python-lsp-jsonrpc" = super.buildPythonPackage rec {
    pname = "python-lsp-jsonrpc";
    version = "1.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cb/d9/656659d5b5d5f402b2b174cd0ba9bc827e07ce3c0bf88da65424baf64af8/python_lsp_jsonrpc-1.1.2-py3-none-any.whl";
      sha256 = "0g5hwadrin0bznmdd51pk2209fkzqklar8dfzl1qks8acglw4fbk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ujson"
    ];
  };
  "python-lsp-server" = super.buildPythonPackage rec {
    pname = "python-lsp-server";
    version = "1.11.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/15/1a222ad69e559487074fa8c9dc4e855ac7338460c6c2e7986af5fa81aeb6/python_lsp_server-1.11.0-py3-none-any.whl";
      sha256 = "1qyzdpsm65nw8vf721r4bmwrwbszzybdqklxr57giacwlqgb9317";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."docstring-to-markdown"
      self."importlib-metadata"
      self."jedi"
      self."pluggy"
      self."python-lsp-jsonrpc"
      self."ujson"
    ];
  };
  "referencing" = super.buildPythonPackage rec {
    pname = "referencing";
    version = "0.34.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/42/8e/ae1de7b12223986e949bdb886c004de7c304b6fa94de5b87c926c1099656/referencing-0.34.0-py3-none-any.whl";
      sha256 = "1m6z2s8ng4sbscizpyp4awkfjsdpnwnaz77s3ygidlyxrq0f6fnm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."rpds-py"
    ];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.31.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl";
      sha256 = "0gq02gh497vhifc00hvz1gpg5absfx8sgg05cpifcw0yq23j3kaq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."charset-normalizer"
      self."idna"
      self."urllib3"
    ];
  };
  "ruff" = super.buildPythonPackage rec {
    pname = "ruff";
    version = "0.3.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/6a/5cdb9e5ae04210ddc5b7b6cf31aeca50654de595e73e59961ce1a662656c/ruff-0.3.7.tar.gz";
      sha256 = "1fp36bi9fkpaz38w80ilg873a3363w1sw028g0k24b0nwnzaxhfm";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "schedule" = super.buildPythonPackage rec {
    pname = "schedule";
    version = "1.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f0/1a/e5a65c08d708ee4c002f3f938ba69b2282af478755700c40f037eacc92ef/schedule-1.2.1-py2.py3-none-any.whl";
      sha256 = "009x0qijhqfkg691qax8mzmgd2xcnahkjxn7dpga2sjr784fpk8l";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl";
      sha256 = "0m02dsi8lvrjf4bi20ab6lm7rr6krz7pg6lzk3xjs2l9hqfjzfwa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "smmap" = super.buildPythonPackage rec {
    pname = "smmap";
    version = "5.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a7/a5/10f97f73544edcdef54409f1d839f6049a0d79df68adbc1ceb24d1aaca42/smmap-5.0.1-py3-none-any.whl";
      sha256 = "1nk95crslxdny5gbgnraryw9x3cwn56pnbd66ilp0gprln7ndn76";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "snowballstemmer" = super.buildPythonPackage rec {
    pname = "snowballstemmer";
    version = "2.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/dc/c02e01294f7265e63a7315fe086dd1df7dacb9f840a804da846b96d01b96/snowballstemmer-2.2.0-py2.py3-none-any.whl";
      sha256 = "06msxjb0qpqgj07zp1drqv19y3afw0m5gr94d3hqlffchdp73qf8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinxcontrib-applehelp" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-applehelp";
    version = "1.0.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/89/fea3fbf6785b388e6cb8a1beaf62f96e80b37311bdeed6e133388a732426/sphinxcontrib_applehelp-1.0.8-py3-none-any.whl";
      sha256 = "1d3761sp84i4jwf68jayw1dpdjp7x4l20sy3bjg387xnq47fnqfb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinxcontrib-devhelp" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-devhelp";
    version = "1.0.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/52/1049d918d1d1c72857d285c3f0c64c1cbe0be394ce1c93a3d2aa4f39fe3b/sphinxcontrib_devhelp-1.0.6-py3-none-any.whl";
      sha256 = "03y9jl2m0zlz02d1y61b7aw45dqqv9dka4gsjg412icl56bd11b4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinxcontrib-htmlhelp" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-htmlhelp";
    version = "2.0.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/e9/74c4cda5b409af3222fda38f0774e616011bc935f639dbc0da5ca2d1be7d/sphinxcontrib_htmlhelp-2.0.5-py3-none-any.whl";
      sha256 = "012yqc5rapjqq6g59p6c0yrn4bw46p74p3a4jcyzblml2bqh8grr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinxcontrib-jsmath" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-jsmath";
    version = "1.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/42/4c8646762ee83602e3fb3fbe774c2fac12f317deb0b5dbeeedd2d3ba4b77/sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl";
      sha256 = "0y1i21qwi5p5f98jxds8r1n12yj12la6nrkkiq3z5wvqzgmymhif";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinxcontrib-qthelp" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-qthelp";
    version = "1.0.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/80/b3/1beac14a88654d2e5120d0143b49be5ad450b86eb1963523d8dbdcc51eb2/sphinxcontrib_qthelp-1.0.7-py3-none-any.whl";
      sha256 = "10l150lybn1ccj9cfwx06kn970sbwckvs7r8ffyzqn1d95f3pbp2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinxcontrib-serializinghtml" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-serializinghtml";
    version = "1.1.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/38/24/228bb903ea87b9e08ab33470e6102402a644127108c7117ac9c00d849f82/sphinxcontrib_serializinghtml-1.1.10-py3-none-any.whl";
      sha256 = "1dvc7z54zzbcf7kp9nbfam8yllbzaynab6prszcd59w0vyw6jqrj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tomli" = super.buildPythonPackage rec {
    pname = "tomli";
    version = "2.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl";
      sha256 = "1k0fqfdylinb57s2aqwprahwbrsk3babg4gghz4g06hnlvky77ck";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tomlkit" = super.buildPythonPackage rec {
    pname = "tomlkit";
    version = "0.12.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/fa/c96545d741f2fd47f565e4e06bfef0962add790cb9c2289d900102b55eca/tomlkit-0.12.4-py3-none-any.whl";
      sha256 = "0yxpzf7afy3m9l4nz3b602ywyrdf42m20i6nz7hxx2fxld42vn2w";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "types-Pygments" = super.buildPythonPackage rec {
    pname = "types-Pygments";
    version = "2.17.0.20240310";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/5a/ee34157d2a6159d79ffc7ebb26adce75b38d185dce211a694076b82852f2/types_Pygments-2.17.0.20240310-py3-none-any.whl";
      sha256 = "1nby3yznqdp3mj5rm9xqg45fdcbkvlgnyl36d6pm5zxa92acl0di";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."types-docutils"
      self."types-setuptools"
    ];
  };
  "types-colorama" = super.buildPythonPackage rec {
    pname = "types-colorama";
    version = "0.4.15.20240311";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/83/6944b4fa01efb2e63ac62b791a8ddf0fee358f93be9f64b8f152648ad9d3/types_colorama-0.4.15.20240311-py3-none-any.whl";
      sha256 = "13hb7b0raihyrbzn421q3vl26s3a00qb5v1igqa3zny0vmhdx4b3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "types-docutils" = super.buildPythonPackage rec {
    pname = "types-docutils";
    version = "0.20.0.20240406";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bd/53/fe423688467176bd4a08b24df8f5c4ae24b2f8e8f81867a34ee80c40e3fc/types_docutils-0.20.0.20240406-py3-none-any.whl";
      sha256 = "04s1w5fkbcwmbiy8sf93zh57vdkcg761wa4rqcki43kw102np5pi";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "types-protobuf" = super.buildPythonPackage rec {
    pname = "types-protobuf";
    version = "5.26.0.20240422";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f2/fb/a1df5e15fb86e0d661569173f46ca193030a309271df3cf03d3cc77360f5/types_protobuf-5.26.0.20240422-py3-none-any.whl";
      sha256 = "0c9qwhdwlr1s1qczq1g1821i2lcbhq1i5iy3xdd1sl22sda2bp74";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "types-pytz" = super.buildPythonPackage rec {
    pname = "types-pytz";
    version = "2024.1.0.20240203";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/6c/42a83a27bef09295b8d26866d690fd50d53b7fa27a961779daf0bb8f3b0c/types_pytz-2024.1.0.20240203-py3-none-any.whl";
      sha256 = "18r13jkvicdypzblsg3ynv0yapmpvfcw28kpxy8szcsx6vqfwycn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "types-setuptools" = super.buildPythonPackage rec {
    pname = "types-setuptools";
    version = "69.2.0.20240317";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1f/22/904934a3344fa5f332ecab887003f3f033c1272432a4af877007b75b0bd3/types_setuptools-69.2.0.20240317-py3-none-any.whl";
      sha256 = "0cbmpw5syylpfymzxc7kc62sd7bw8a84s39zbiig0yxbhxygz4fg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.11.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/01/f3/936e209267d6ef7510322191003885de524fc48d1b43269810cd589ceaf5/typing_extensions-4.11.0-py3-none-any.whl";
      sha256 = "0yiqq03194im2vnsakm10rli5n3rbf6mbdsvfz7g9nkyi5r4vyf1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ujson" = super.buildPythonPackage rec {
    pname = "ujson";
    version = "5.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6e/54/6f2bdac7117e89a47de4511c9f01732a283457ab1bf856e1e51aa861619e/ujson-5.9.0.tar.gz";
      sha256 = "0cjmww3rz56gwg3rybic16nmcwfj9aqywxc5yjkvh0am7pkr5k49";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "2.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a2/73/a68704750a7679d0b6d3ad7aa8d4da8e14e151ae82e6fee774e6e0d05ec8/urllib3-2.2.1-py3-none-any.whl";
      sha256 = "17gsqhr25vrbl1h9mxbgnmqnwlc062vl5zwb29vp0ika57n202s5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "3.18.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/da/55/a03fd7240714916507e1fcf7ae355bd9d9ed2e6db492595f1a67f61681be/zipp-3.18.2-py3-none-any.whl";
      sha256 = "0kipymdxv3nhx8rp3xd25baj59xhpswg2ak2n1164ygbb6w9gqfw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-dotenv" = super.buildPythonPackage rec {
    pname = "python-dotenv";
    version = "1.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6a/3e/b68c118422ec867fa7ab88444e1274aa40681c606d59ac27de5a5588f082/python_dotenv-1.0.1-py3-none-any.whl";
      sha256 = "f7b63ef50f1b690dddf550d03497b66d609393b40b564ed0d674909a68ebf16a";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
